[book]
authors = ["rabbitprincess"]
language = "ko"
multilingual = false
src = "src"
title = "비트코인, 돈이 될까?"

[build]
build-dir = "output"

[output.html]
site-url = "https://rabbitprincess.github.io/bitcoin-ebook/"