services:
  mdbook:
    build:
      context: .
    image: dreamcacao/mdbook:v0.0.1
    pull_policy: always
    ports:
      - "3000:3000"
    volumes:
      - ./src:/book/src
      - ./book.toml:/book/book.toml
    command: [ "mdbook", "serve", "--hostname", "0.0.0.0" ]
